### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by kuchune**
test add reviewers

### CODE REVIEW

**Review by feixue-ckux — APPROVED** [review]
yes

**Comment by ckux** [comment]
检测到敏感词getcap,setcap,lshw,dmidecode变动:

**Review by ckux — APPROVED** [review]
1111

**Review by ckux — APPROVED** [review]
222

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
Debian检查:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
[Debian检查]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
11111

**Comment by kuchune** [comment]
`date`

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
debian/changelog版本检查失败:4:5.27.2.201-deepin200-1|4:5.27.2.201-deepin201-1
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:['debian/test.log']
检测到敏感词dmidecode/lshw变动
检测到敏感词export/unset变动

**Comment by kuchune** [comment]
\[Debian检查\]:
检测到debian目录文件有变更:debian/test.log
检测到敏感词dmidecode,lshw变动
检测到敏感词export,unset变动

**Pull request closed without merging**
